Lekarze/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lekarze.Models
{
    public class Doctor
    {
        public int DoctorID { get; set; }
        public string DoctorName { get; set; }
        public string DoctorLastName { get; set; }
        public int GenreId { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual ICollection<Visit> Visit { get; set; }
    }
}

Lekarze/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lekarze.Models
{
    public class Genre
    {
        public int GenreId { get; set; }
        public string GenreName { get; set; }

        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}

Lekarze/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lekarze.Models
{
    public class Person
    {
        public int PersonId { get; set; }

        [Required(ErrorMessage = "*Pole Wymagane")]
        [Display(Name = "Imię")]
        public string Name { get; set; }

        [Required(ErrorMessage = "*Pole Wymagane")]
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        public virtual ICollection<Visit> Visit { get; set; }
    }
}

Lekarze/Models/Visit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lekarze.Models
{
    public class Visit
    {
        public int VisitId { get; set; }
        public string Day { get; set; }
        public DateTime Time { get; set; }
        public int? PersonId { get; set; }
        public int DoctorId { get; set; }

        public virtual Person Person { get; set; }
        public virtual Doctor Doctor { get; set; }        
    }
}

Lekarze/ViewModels/ConfirmViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Lekarze.Models;

namespace Lekarze.ViewModels
{
    public class ConfirmViewModel
    {
        public Visit Visit { get; set; }
        public Doctor Doctor { get; set; }
        public Person Person { get; set; }
    }
}

Lekarze/ViewModels/DoctorsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lekarze.Models;

namespace Lekarze.ViewModels
{
    public class DoctorsViewModel
    {
        public Doctor Doctor { get; set; }
        public List<Doctor> List { get; set; }
        public IEnumerable<Genre> Genre { get; set; }
    }
}

Lekarze/Controllers/ClinicController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lekarze.DAL;
using Lekarze.Models;
using Lekarze.ViewModels;

namespace Lekarze.Controllers
{
    public class ClinicController : Controller
    {
        private ClinicContext db = new ClinicContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register(Doctor doctor)
        {           
            var vm = new DoctorsViewModel()
            {
                Doctor = doctor,
                Genre = db.Genre.ToList()
            };

            return View(vm);
        }

        [ChildActionOnly]
        public ActionResult Register2(int id)
        {
            var list = db.Doctors.ToList();

            if (id !=0)
                list = db.Doctors.Where(n=>n.GenreId == id).ToList();

            var vm = new DoctorsViewModel()
            {
                List = list,
                Genre = db.Genre.ToList()
            };
            
            return PartialView("_ListaLekarzy", vm);
        }

        public ActionResult RegisterDay(int id)
        {
            var doktor = db.Doctors.SingleOrDefault(d=> d.DoctorID == id);

            if (doktor == null)
                return HttpNotFound(); 

            ViewBag.listaDni = db.Visits.ToList().Where(n => n.DoctorId == id).Select(n => n.Day).Distinct();

            return View(doktor);
        }

        [ChildActionOnly]
        public ActionResult Termins(string day, int id)
        {
            var listaGodzin = db.Visits.ToList()
                .Where(n => n.DoctorId == id && n.Day.Equals(day) && n.PersonId == null)
                .Select(n => n);
            return PartialView("_ListaPrzyjec", listaGodzin);

        }

        public ActionResult Confirm(int id)
        {
            var wizyta = db.Visits.SingleOrDefault(w=> w.VisitId == id);
            if (wizyta == null)
                return HttpNotFound();
            var vm = new ConfirmViewModel()
            {
                Visit = wizyta,
                Doctor = db.Doctors.SingleOrDefault(d=>d.DoctorID == wizyta.DoctorId)
            };
           
            return View(vm);
        }

        [HttpPost]
        public ActionResult Confirmed(ConfirmViewModel confirm)
        {
            if (!ModelState.IsValid)
            {
                var vm = new ConfirmViewModel()
                {
                    Visit= confirm.Visit,
                    Doctor = db.Doctors.SingleOrDefault(d => d.DoctorID == confirm.Visit.DoctorId)
                };
                return View("Confirm", vm);
            }

            db.Persons.Add(confirm.Person);
            var visitInDb = db.Visits.SingleOrDefault(v => v.VisitId == confirm.Visit.VisitId);
            if (visitInDb == null)
                return HttpNotFound();
            visitInDb.PersonId = confirm.Person.PersonId;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Lekarze/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lekarze.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lekarze/Views/Clinic/Confirm.cshtml
@model Lekarze.ViewModels.ConfirmViewModel

@{
    ViewBag.Title = "Confirm";
}
<h3>@ViewBag.potwierdzenie</h3>
<br />
<h5>Aktualna godzina: <span id="clock">--:--:--</span></h5>
<br />
@using (Html.BeginForm("Confirmed","Clinic"))
{
    <div class="h3">
        Twoje dane:
    </div>
    <br/>
    <div class="form-group">
        @Html.LabelFor(n => Model.Person.Name)
        @Html.TextBoxFor(n => Model.Person.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => Model.Person.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(n => Model.Person.LastName)
        @Html.TextBoxFor(n => Model.Person.LastName, new { @class="form-control" })
        @Html.ValidationMessageFor(n => Model.Person.LastName)
    </div>
    <br />
    @Html.HiddenFor(n=> Model.Visit.VisitId)
    @Html.AntiForgeryToken()
    <input id="Button1" class="btn btn-primary" type="submit" value="Potwierdź" />
}

@section scripts{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/Clock.js"></script>
}

Lekarze/Views/Clinic/Confirmed.cshtml
@{
    ViewBag.Title = "Confirmed";
}

<h2>Wizyta dodana.</h2>

Lekarze/Views/Clinic/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>Aplikacja do rejstrowania wizyt u lekarza.</h3>
<p id="clock"></p>

<button type="button" id="js-click"> Zerejestruj </button>

@section scripts{
    <script src="~/Scripts/Clock.js"></script>
    <script>
        $(document).ready(function () {
            $("#js-click").on("click", function () {
                location.href = '@Url.Action("Register")';
            });
        });
    </script>
}

Lekarze/Views/Clinic/Register.cshtml
@model Lekarze.ViewModels.DoctorsViewModel

@{
    ViewBag.Title = "Register";
}

<h2 align="center">Rejestracja</h2>
<br />

<div align="center">
    @using (Html.BeginForm("Register", "Clinic"))
    {
        @Html.DropDownListFor(m => m.Doctor.GenreId, new SelectList(Model.Genre, "GenreId", "GenreName"), "Wszyscy lekarze", new { @class = "form-control" })
    }
</div>

<div align="center">
    @Html.Action("Register2", new { id = Model.Doctor.GenreId })
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("select").on("change", function () {
                $("form").trigger("submit");
            });
        });
    </script>
}

Lekarze/Views/Clinic/RegisterDay.cshtml
@model Lekarze.Models.Doctor

@{
    ViewBag.Title = "RegisterDay";
}

<h2>Rejestracja</h2>

<div>    
    <hr />
    <h4>Doktor</h4>
    <dl class="dl-horizontal">
        <dt>
            Imię:
        </dt>

        <dd>
            @Html.DisplayFor(m => Model.DoctorName)
        </dd>

        <dt>
            Nazwisko:
        </dt>

        <dd>
            @Html.DisplayFor(m=> Model.DoctorLastName)
        </dd>

        <dt>
            Rodzaj:
        </dt>

        <dd>
            @Html.DisplayFor(m => Model.Genre.GenreName)
        </dd>

    </dl>
</div>
<h4>Dostępne terminy:</h4>

@foreach(var days in ViewBag.listaDni)
{
    <h5>@days:</h5>
    @Html.Action("Termins", new { day = days, id = Model.DoctorID })
}

<br/>
<p>    
    @Html.ActionLink("Wróć do listy", "Register")
</p>

Lekarze/Views/Clinic/_ListaLekarzy.cshtml
@model Lekarze.ViewModels.DoctorsViewModel


<table class="table">
    <tr>
        <th>
            Imię
        </th>
        <th>
            Nazwisko
        </th>
        <th>
            Rodzaj
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.List)
    {
        <tr>
            <td>
                @Html.DisplayFor(m => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(m => item.DoctorLastName)
            </td>
            <td>
                @Html.DisplayFor(m => item.Genre.GenreName)
            </td>
            <td>
                @Html.ActionLink("Zarejestruj", "RegisterDay", new { id = item.DoctorID })
            </td>
        </tr>
    }

</table>

Lekarze/Views/Clinic/_ListaPrzyjec.cshtml
@model IEnumerable<Lekarze.Models.Visit>

    <ul>
        @foreach (var hour in Model)
        {
            
            <li>
                @hour.Time.ToString("H:mm")
                @Html.ActionLink("Wybierz", "Confirm", new { id = hour.VisitId })
            </li>
        }
    </ul>

Lekarze/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lekarze/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lekarze/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lekarze/Views/Shared/View.cshtml
@model IEnumerable<Lekarze.Models.Doctors>

<ul>
    @foreach (var item in Model)
    {
        <li>@item.Name @item.LastName</li>
    }
</ul>

Lekarze/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Przychodnia", "Index", "Clinic", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Rejestracja", "Register", "Clinic")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>